config/routes.rb
Rails.application.routes.draw do  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users
  devise_for :users, controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  resources :users, only: [:index, :show]  
  resources :stocks, only: %i(index create destroy)
  resources :articles do
    collection do
      get :guide
      get :iine_rank
      get :trend_line
    end
    resources :comments
  end
  resources :stocks do
    collection do
      get :guide
    end
  end
  resources :relationships, only: [:create, :destroy]

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  post 'like/:id' => 'likes#create_stock', as: 'create_like_stock'
  delete 'like/:id' => 'likes#destroy_stock', as: 'destroy_like_stock'

  root to: "articles#top"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  resources :tags
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article, only: [:create, :edit, :update]
  def create
    
    @comment = @article.comments.build(comment_params)
    @comment.user_id = current_user.id
    
    respond_to do |format|
      
      if @comment.save
        
        format.js { render :index }
      else
        format.html { redirect_to article_path(@article), notice: 'コメントを入力してください' }
      end
    end
  end
  def edit
    @comment = @article.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end
  def update
    @comment = @article.comments.find(params[:id])
      respond_to do |format|
        if @comment.update(comment_params)
          flash.now[:notice] = 'コメントが編集されました'
          format.js { render :index }
        else
          flash.now[:notice] = 'コメントの編集に失敗しました'
          format.js { render :edit_error }
        end
      end
  end
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= form_with(model: [article, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, id: "comment_content_#{article.id}" %>
    <%= form.label :content %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [article, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, placeholder: "コメントを入力してください", :size => "40*40" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
  <br>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <% if comment.user.image? %>
        <img src=<%= comment.user.image %> class = "icon_image">
      <% else %>
        <img src="/assets/default.png" class = "icon_image">
      <% end %>
      <span class="comment-user">
        <b><%= comment.user.name %></b>
      </span>
      <span class="comment-created">
        <%= comment.created_at.strftime('%Y-%m-%d %H:%M') %>に投稿
      </span>
      <% if comment.user == current_user %>
        <%= link_to "", edit_article_comment_path(article, comment), remote: true, class: "glyphicon glyphicon-edit" %>
        <%= link_to "", article_comment_path(comment.article_id, comment.id), method: :delete, remote: true,
                                          data: { confirm: "本当に削除しますか?"}, class: "glyphicon glyphicon-trash delete-icon" %>
      <% end %>
      <li>
        <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
        <%= comment.content %> 
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', article: @article, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.article.comments, article: @comment.article }) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");