config/routes.rb
Rails.application.routes.draw do  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users
  devise_for :users, controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  resources :users, only: [:index, :show]  
  resources :stocks, only: %i(index create destroy)
  resources :articles do
    collection do
      get :guide
      get :iine_rank
      get :trend_line
    end
    resources :comments
  end
  resources :stocks do
    collection do
      get :guide
    end
  end
  resources :relationships, only: [:create, :destroy]

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  post 'like/:id' => 'likes#create_stock', as: 'create_like_stock'
  delete 'like/:id' => 'likes#destroy_stock', as: 'destroy_like_stock'

  root to: "articles#top"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  resources :tags
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  is_impressionable counter_cache: true
  has_many :stocks, dependent: :destroy
  has_many :stock_users, through: :stocks, source: :user
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  scope :search_title, -> (title) { where("title LIKE ?", "%#{title}%") }

  validates :title, presence: true
  validates :content, presence: true
  # 現在ログインしているユーザーidを受け取り、記事をストックする
  def stock(user)
    stocks.create(user_id: user.id)
  end
  
  # 現在ログインしているユーザーidを受け取り、記事のストックを解除する
  def unstock(user)
    stocks.find_by(user_id: user.id).destroy
  end
  
  # 記事がストック済みであるかを判定、取得済みであれば true を返す
  def stocked?(user)
    stock_users.include?(user)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  # before_action :authenticate_user!, except: :top, except: :guide
  before_action :authenticate_user!, except: [:top, :guide]
  impressionist actions: [:index, :show]

  
  def index
    @articles = Article.all.order(created_at: "DESC")
    @articles = Article.all.search_title(params[:search_title]).page(params[:page]) if params[:search_title].present? 
    @rank_articles = Article.order(impressions_count: 'DESC')
  end

  def show
    @article = Article.find(params[:id])
    impressionist(@article, nil, unique: [:ip_address]) 
    @comments = @article.comments
    @comment = @article.comments.build
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = current_user.articles.build(article_params) 

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "記事を作成しました" }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "記事を更新しました" }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "記事を削除しました" }
      format.json { head :no_content }
    end
  end

  def top
  end

  def guide
  end

  def iine_rank
  end
  
  def trend_line
  end

  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :impressions_count, :user_id, { tag_ids: [] })
    end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<% if article.user.image? %>


  <td class="align-middle">
    <img src=<%= article.user.image %> class = "icon_image">
  </td>
<% else %>
  <td class="align-middle">
    <img src="/assets/default.png" class = "icon_image">
  </td>
<% end %>


<td class="align-middle"><%= article.user.name %></td>

<td class="align-middle title_size">  
  <%= link_to((article), class: "article_link") do %>
    <%= article.title.truncate(40) %>
  <% end %>
</td>
<%# <td class="align-middle"> %>
  <%#= link_to((article), class: "article_link") do %>
    <%#= article.content.truncate(30) %>
  <%# end %>
<%# </td> %>

<td class="align-middle">
  <% article.tags.each do |tag| %>
    <i class="fas fa-tags"><%= tag.name %></i>
    <% if article.tags.count >= 2 %>
      <%= "..." %>
    <% end %>
    <% break %>
  <% end %>
  
</td>
<td class="align-middle"><i class="fas fa-eye"></i><%= article.impressions_count %></td>


<% if current_user.liked_by?(article.id) %>
  <td class="align-middle heart">
    <%= link_to destroy_like_path(article), class: "like-link", method: :DELETE, remote: true do %>
      <i class="fa fa-heart unlike-btn"></i>
    <% end %>
    <%= article.likes.count %>
  </td>
<% else %>
  <td class="align-middle heart">
    <%= link_to create_like_path(article), class: "like-link", method: :POST, remote: true do %>
      <i class="fa fa-heart like-btn"></i>
    <% end %>
    <%= article.likes.count %>
  </td>
<% end %>
<td class="align-middle">
  <div id="article-<%= article.id %>"><%= render partial: 'stocks/stock', locals: { article: article } %></div>
</td>

<%# <td> %>
<%#= render partial: "articles/follow_form", locals: { user: article.user } %>
<%# </td>  %>

<%# <td> %>
<%#= link_to '詳細', article, class: 'btn btn-default' %>
<%# </td> %>
<% if article.user == current_user %>
<td class="align-middle"><%= link_to "", edit_article_path(article), class: "glyphicon glyphicon-edit" %></td>
<td class="align-middle"><%= link_to "", article, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "glyphicon glyphicon-trash delete-icon" %></td>
<% end %>


 

app/views/articles/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">

  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "フォローを解除" %>
    <% end %>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <%# <h2> %>
        <%#= pluralize(article.errors.count, "error") %>
        <%# prohibited this article from being saved: %>
      <%# </h2> %>
      <br>
      <br>
      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title, placeholder: "タイトルを入力してください", size: "140x10" %>
  </div>
  <br>
  <div class="tag_field">
    <% Tag.all.each do |tag| %>
      <%= form.check_box :tag_ids, { multiple: true, checked: tag[:checked], disabled: tag[:disabled], include_hidden: false }, tag[:id] %>
      <%= tag.name %>
    <% end %>  
  </div>
  <br>
  <br>
  <div class="field">
    <%= form.label :content %>
    <br>
    <%= form.text_area :content, placeholder: "内容を入力してください（マークダウン記法対応）", size: "140x20" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/iine_rank.html.erb
<th>icon</th>

app/views/articles/index.html.erb
<br>

<div class="container">
  <div class="row">
    <div class="column col-lg-2">
      <div class="rankking">
      <%# <hr> %>
      <h3> HOME </h3>
      <br>
      <% if user_signed_in? %>
        <%= form_with(model: @article, method: :get, local: true, ) do |form| %>
          <%= form.text_field :search_title, placeholder:"記事タイトル検索",  size: "20x60" %>
          <br>
          <br>
          <%= form.submit '検索' , name: 'search', class:"btn btn-warning" %>
        <% end %>
      <% end %>
      <%#= link_to '記事一覧', articles_path, {class: "index_link"} if user_signed_in? %>
      <%# <br> %>
      <%# <br> %>
      <%# <br> %>
      <br>
      <br>
      <%= link_to 'いいねランキング', iine_rank_articles_path, class:"btn btn-outline-primary" if user_signed_in? %>
      <br>
      <br>
      <br>
      <%= link_to 'トレンドライン', trend_line_articles_path, class:"btn btn-outline-primary" if user_signed_in? %>
      <%# <h3> PV数ランキング </h3> %>
      <%# @rank_articles.each do |t| %>
        <%# PV数 %>
        <%#= t.impressions_count %>
      <%# end %>
      <br>
      <br>
      <br>
      <%#= link_to 'ユーザー一覧', users_path if user_signed_in? %>
      <%# <hr> %>
    </div>
    </div>
    <div class="column col-lg-10">
      <table class="table table-hover" >
        <thead>
          <tr>
            <th>icon</th>
            <th>ニックネーム</th>
            <th>Title</th>
            <%# <th>Content</th> %>
            <th> タグ </th>
            <th> 閲覧数 </th>
            <th> いいね </th>
            <th> ストック </th>
          </tr>
        </thead>

        <tbody>
          <% @articles.each do |article| %>
            <tr id="article_<%= article.id %>">
              <%= render 'article', article: article %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<br>
<h1>記事を投稿する</h1>

<%= render 'form', article: @article %>
<br>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% if @article.user.image? %>
  <td class="align-middle">
    <img src=<%= @article.user.image %> class = "icon_image">
  </td>
<% else %>
  <td class="align-middle">
    <img src="/assets/default.png" class = "icon_image">
  </td>
<% end %>
<br>
<br>
<strong>ニックネーム</strong>
<div class="text-primary">
  <strong><%= @article.user.name %></strong>
</div>
<br>
<br>
<p>
  <strong>Title</strong>
</p>
<div class="show_title">
  <%= @article.title %>
</div>
<br>
<br>
<br>
<p>
  <strong>タグ一覧</strong>
</p>
<div class="show_tag">
   <% @article.tags.each do |tag| %>
    <i class="fas fa-tags"></i><%= tag.name %>
  <% end %>
</div>
<br>
<br>
<br>
<p>
  <strong>Content</strong>
</p>
<div class="show_content">
<p>
  <%= markdown(@article.content) %>
</p>
</div>

<br>
<br>
<p class="impression_rspec">
  <strong>閲覧数</strong>
  <i class="fas fa-eye"></i><%= @article.impressions_count %>
  
</p>
<br>
<div id="article-<%= @article.id %>">
    <%= render partial: 'stocks/stock', locals: { article: @article } %>
</div>
<br>
<br>
<hr width="70%">
<p>コメント一覧</p>

<!-- このcomments_areaというHTMLのidを取得して、そのdivの部分だけを更新する -->
<div id="comments_area">
  <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
<%= render partial: 'comments/index', locals: { comments: @comments, article: @article } %>
</div>

<!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
<%= render partial: 'comments/form', locals: { comment: @comment, article: @article } %>

<%= link_to 'Edit', edit_article_path(@article) %> |

<%= link_to 'Back', :back %>

app/views/articles/top.html.erb
<%= image_tag '/assets/stock.webp', size: '100x400', class:"card-img-top" %>
<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-12">      
        <div class="top_explain">
          <h5>
            <strong>
            <br>
            Market Recordは投資に関する知識を記録・共有するためのサービスです。
            <br>
            <br>
            投資家の皆さんの銘柄選びや、決算書の読み方、売買タイミング、リスク管理など
            <br>
            <br>
            投資に必要なノウハウを共有することができます。
            <br>
            <br>
            知識を共有し、自分の考えを整理することで、
            <br>
            <br>
            再現性のある投資スキルの発見や、金融リテラシーの向上に繋がります。
            <br>
            <br>
            ユーザーの皆さんと一緒に、価値ある情報が集まるコミュニティを創出しましょう。
            </strong>
            <br>
            <br>            
            <hr>
            <br>
            <div class="tops-footer"><%= link_to "Market Recordの使い方", guide_articles_path, class:"btn btn-outline-info" %></div>
          </h5>
        </div>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="row">    
    <div class="col-md-12">
      <% if  user_signed_in? %>
        <div>
          <%= link_to " 記事一覧 ", articles_path, class:"btn btn-outline-primary" %>
        </div>
      <% else %>
        <div>
          <%= link_to " アカウント作成 ", new_user_registration_path, class:"btn btn-outline-primary" %>
        </div>
        <br>
        <div>
          <%= link_to " ログインする ", new_user_session_path, class:"btn btn-outline-primary" %>
        </div>
        <br>
        <div>
        <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class:"btn btn-outline-primary" %>
        </div>
        <br>
        <div>
        <%= link_to '管理者ゲストログイン', users_guest_admin_sign_in_path, method: :post, class:"btn btn-outline-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/trend_line.html.erb
<h2>test</h2>