config/routes.rb
Rails.application.routes.draw do  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :users
  devise_for :users, controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  resources :users, only: [:index, :show]  
  resources :stocks, only: %i(index create destroy)
  resources :articles do
    collection do
      get :guide
      get :iine_rank
      get :trend_line
    end
    resources :comments
  end
  resources :stocks do
    collection do
      get :guide
    end
  end
  resources :relationships, only: [:create, :destroy]

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

  post 'like/:id' => 'likes#create_stock', as: 'create_like_stock'
  delete 'like/:id' => 'likes#destroy_stock', as: 'destroy_like_stock'

  root to: "articles#top"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end
  resources :tags
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability
  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  is_impressionable counter_cache: true
  has_many :stocks, dependent: :destroy
  has_many :stock_users, through: :stocks, source: :user
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  scope :search_title, -> (title) { where("title LIKE ?", "%#{title}%") }

  validates :title, presence: true
  validates :content, presence: true
  # 現在ログインしているユーザーidを受け取り、記事をストックする
  def stock(user)
    stocks.create(user_id: user.id)
  end
  
  # 現在ログインしているユーザーidを受け取り、記事のストックを解除する
  def unstock(user)
    stocks.find_by(user_id: user.id).destroy
  end
  
  # 記事がストック済みであるかを判定、取得済みであれば true を返す
  def stocked?(user)
    stock_users.include?(user)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :user_id, presence: true
  validates :article_id, presence: true

  # ストック一覧表示用  
  def self.get_stock_articles(user)
    self.where(user_id: user.id).map(&:article)
  end
  scope :search_title, -> (title) { where("title LIKE ?", "%#{title}%") }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { maximum: 50 }, on: :create

  has_many :articles, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes
  has_many :comments

  
  def liked_by?(article_id)
    likes.where(article_id: article_id).exists?
  end

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  #フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  mount_uploader :image, ImageUploader
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  def self.admin_guest
    find_or_create_by!(name: '管理者ゲスト',email: 'admin_guest@example.com', admin: true) do |user|
      user.password = SecureRandom.alphanumeric()
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :article_params

  def create
    Like.create(user_id: current_user.id, article_id: params[:id])
  end

  def create_stock
    Like.create(user_id: current_user.id, article_id: params[:id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, article_id: params[:id]).destroy
  end

  def destroy_stock
    Like.find_by(user_id: current_user.id, article_id: params[:id]).destroy
  end

  private
  def article_params
    @article = Article.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/markdown_helper.rb
require 'rouge/plugins/redcarpet'

class HTML < Redcarpet::Render::HTML
  include Rouge::Plugins::Redcarpet
end

module MarkdownHelper
  def markdown(text)
    options = {
      no_images:     true,
      no_styles:     true,
      with_toc_data: true,
      hard_wrap:     true
    }

    extensions = {
      no_intra_emphasis:   true,
      tables:              true,
      fenced_code_blocks:  true,
      autolink:            true,
      lax_spacing:         true,
      space_after_headers: true
    }

    unless @markdown
      # Redcarpet::Render::HTML => HTML に変更
      renderer = HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer, extensions)
    end

    @markdown.render(text).html_safe
  end

  def toc(text)
    markdown = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML_TOC.new(nesting_level: 3)
    )
    markdown.render(text).html_safe
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Martket Record</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="main">
      <header class="clearfix">
        <ul>
          <li class="left1">
          <% if user_signed_in? %>
            <%= link_to 'Market Record', articles_path, class: "link"%>
          <% else %>  
            <%= link_to 'Market Record', root_path, class: "link"%>
            <% end %>
          </li>
          <%# <li class="left2"> %>
          <%# if controller.controller_name == "articles" %>
            <%# if user_signed_in? %>
              <%#= form_with(model: @article, method: :get, local: true, ) do |form| %>
                <%#= form.text_field :search_title, placeholder:"記事タイトル検索" %>
                <%#= form.submit '検索' , name: 'search', class:"btn btn-warning" %>
              <%# end %>
            <%# end %>
          <%# end %>
          <%# </li> %>
          
          <div class="float_right">
            <li class="right_article_post"><%= link_to '記事を投稿する', new_article_path, class:"btn btn-warning btn-lg" if user_signed_in? %></li>
            <% if user_signed_in? %>
            <li class="right_icon">
              <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-address-card size_top_icon"></i>
              </a>
              
              <ul class="dropdown-menu">
                  <li><%= link_to "Market Recordの使い方", guide_articles_path %></li>
                  <li><%= link_to "アカウント編集", edit_user_registration_path %></li>
                  <%# <li> %>
                    <%#= link_to "お気に入りユーザー一覧", stocks_path, class: "glyphicon glyphicon-thumbs-up" %>
                  <%# </li> %>
                  <li><%= link_to "ストック記事一覧", stocks_path, class: "glyphicon glyphicon-paperclip" %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-ok" %></li>
                  <%# <li> %>
                    <%#= link_to "退会処理", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-pencil" %>
                  <%# </li> %>
                <% if user_signed_in? %>
                  <% if current_user.admin? %>
                  <li role="separator" class="divider"></li>
                  <li><a><%= link_to "管理画面", rails_admin_path %></a></li>
                  <% end %>
                <% end %>
              </ul>
              
            </li>
            <% end %>  
          </div>  
        </ul>
      </header>
      
      
      <br>
      <br>
      <%= yield %>
      <br>
      <br>
      <footer>
        <p class="footer-text">Copyright 2021 Market Record All Rights Reserved.</p>
      </footer>
    </div>  
  </body>
</html>